app.name=Biblio
app.version=1.0.1
app.channel=stable
analytics.url=http://kaytodo.infinityfree.me/api/biblio/analytics
update.url=http://kaytodo.infinityfree.me/api/biblio/update
# analytics.url=http://127.0.0.1:8000/api/biblio/analytics
# update.url=http://127.0.0.1:8000/api/biblio/update
